# Change these first
owner: lexNwimue # Your GitHub organization or username, where this repository lives
repo: filmhouse-monitor # The name of this repository

sites:
  - name: Filmhouse Frontend
    url: https://www.filmhouseng.com
  - name: Filmhouse Backend
    url: https://fh-api.filmhouseng.com
  - name: Movie List
    url: https://fh-api.filmhouseng.com/movie/new-list?cinema_id=12&start_date=2023-09-14&end_date=2023-09-14&platforn=WEB
  - name: Cinema List
    url: https://fh-api.filmhouseng.com/cinema
  - name: Movie Banners
    url: https://fh-api.filmhouseng.com/movie/movie-banners?platform=WEB
  - name: Coming Soon
    url: https://fh-api.filmhouseng.com/movie/new-coming-soon?platform=WEB

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /filmhouse-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Filmhouse Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
