# Change these first
owner: lexNwimue # Your GitHub organization or username, where this repository lives
repo: filmhouse-monitor # The name of this repository

sites:
  - name: Filmhouse Frontend
    url: https://www.filmhouseng.com
  - name: Filmhouse Backend
    url: https://fh-api.filmhouseng.com
    expectedStatusCodes:
      - 404
  - name: Movie List
    url: https://fh-api.filmhouseng.com/movie/new-list?cinema_id=12&start_date=2023-10-07&end_date=2023-10-07&platforn=WEB
  - name: Cinema List
    url: https://fh-api.filmhouseng.com/cinema
  - name: Movie Banners
    url: https://fh-api.filmhouseng.com/movie/movie-banners?platform=WEB
  - name: Coming Soon
    url: https://fh-api.filmhouseng.com/movie/new-coming-soon?platform=WEBz

assignees: 
  - lexNwimue

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: night
  baseUrl: /filmhouse-monitor
  logoUrl: https://www.filmhouseng.com/images/FHC%20LOGO.png
  name: Filmhouse Status
  introTitle: "**Upptime** - The Ultimate Cinema Experience"
  introMessage: This stage page keeps track of the status of all Filmhouse software infrastructure! [**Visit**](https://fh-api.filmhouseng.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
